---
- hosts: webserver
  become: true
  become_user: root
  vars:
    repo_path: 
    dest_path: /tmp/gitRepo
  tasks:
  - name: Install Multiple packageson host server
    yum: name={{item}} state=present
    loop:
    - git
    - docker
  - name: Start the docker service
    service: name=docker state=started
  - name: Clone the Git Repo
    git: repo={{repo_path}} dest={{dest_path}}
  - name: Build Dockerfile
    command: chdir={{dest_path}} docker build -t ansiblejenkins
  - name: Run the the Image to deploy App
    command: docker run -d -P ansiblejenkins
